# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- main
- develop
- feature/*
- bugfix/*

pool:
  name: 'Test'
  artifaceName: drop

variables:
  config: 'Release'

stages:
- stage: 'Build'
  jobs:
  - job: 'DockerBuild'
    steps:
    - task: Docker@2
      inputs:
        containerRegistry: 'Docker'
        repository: 'walmartpayment'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'


